#!/bin/sh
#
#

# Convention of Linux type VM on Azure is 30G
export VMSIZE=30g

# Set to a list of packages to install.
export VM_EXTRA_PACKAGES="azure-agent python python3 firstboot-freebsd-update firstboot-pkgs net/cloud-init"

# Set to a list of third-party software to enable in rc.conf(5).
export VM_RC_LIST="ntpd sshd waagent firstboot_freebsd_update firstboot_pkgs cloudinit"

# No swap space; waagent will allocate swap space on the resource disk.
# See ResourceDisk.EnableSwap and ResourceDisk.SwapSizeMB in waagent.conf
export NOSWAP=YES

# https://learn.microsoft.com/en-us/partner-center/marketplace/azure-vm-certification-faq#vm-images-must-have-1-mb-of-free-space
export VM_BOOTPARTSOFFSET=1M

vm_extra_pre_umount() {
	mount -t devfs devfs ${DESTDIR}/dev

	# The firstboot_pkgs rc.d script will download the repository
	# catalogue and install or update pkg when the instance first
	# launches, so these files would just be replaced anyway; removing
	# them from the image allows it to boot faster.
	chroot ${DESTDIR} ${EMULATOR} env ASSUME_ALWAYS_YES=yes \
		/usr/sbin/pkg delete -f -y pkg
	rm -r ${DESTDIR}/var/db/pkg/repos/FreeBSD

	chroot ${DESTDIR} ${EMULATOR} pw usermod root -h -

	umount ${DESTDIR}/dev

	cat << EOF >> ${DESTDIR}/etc/rc.conf
ifconfig_hn0="SYNCDHCP"
ntpd_sync_on_start="YES"
EOF

    # Configure cloud-init
    cat <<-'EOF' > ${DESTDIR}/usr/local/etc/cloud/cloud.cfg.d/98_azure.cfg
        disable_root: true
        expire: false
        users:
          - name: ci-user
            lock-passwd: true
            sudo: "ALL=(ALL) NOPASSWD:ALL"
            groups: wheel
            shell: /bin/sh
            ssh_authorized_keys:
              - ssh-rsa AAAAB3NzakP6XuEDl3ZzgywRvjpS9t50oHL+rfFw/CyhRY0=

        runcmd:
          - mkdir /run/tests
        write_files:
          - path: /run/tests/test-script.sh
            permissions: '0755'
            content: |
              #!/bin/bash
              echo "Running my custom script"
              date > /run/tests/script-run-time.txt
        runcmd:
          - [ bash, /run/tests/test-script.sh ]
EOF

	cat << EOF >> ${DESTDIR}/boot/loader.conf
autoboot_delay="-1"
beastie_disable="YES"
loader_logo="none"
hw.memtest.tests="0"
console="comconsole efi vidconsole"
comconsole_speed="115200"
boot_multicons="YES"
boot_serial="YES"
mlx4en_load="YES"
mlx5en_load="YES"
EOF


        cat << EOF > ${DESTDIR}/usr/local/etc/waagent.conf
Extensions.Enabled=y
Provisioning.Agent=auto
Provisioning.DeleteRootPassword=y
Provisioning.RegenerateSshHostKeyPair=y
Provisioning.SshHostKeyPairType=rsa
Provisioning.MonitorHostName=y
Provisioning.DecodeCustomData=y
Provisioning.ExecuteCustomData=y
ResourceDisk.Format=y
ResourceDisk.Filesystem=ufs
ResourceDisk.MountPoint=/mnt/resource
ResourceDisk.EnableSwap=y
ResourceDisk.SwapSizeMB=2048
ResourceDisk.MountOptions=None
Logs.Verbose=y
OS.EnableFIPS=n
OS.RootDeviceScsiTimeout=300
OS.OpensslPath=None
OS.SshDir=/etc/ssh
OS.PasswordPath=/etc/master.passwd
OS.SudoersDir=/usr/local/etc/sudoers.d
OS.EnableFirewall=y
EOF

	touch ${DESTDIR}/firstboot

	return 0
}
